title: <p align="center"> Angat Sitoula </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/angatsitoula">LinkedIn</a> |
  <a href="https://github.com/Angat1">GitHub</a>
  
  <br>   
  I'm working on Data Science,  Spark, Machine learning & NLP related problems..
  <br>
  </p>


theme: jekyll-theme-minimal
